#!/bin/bash

TMP_FILE=/tmp/applauncher

open() {
    ~/.config/i3/scripts/polybar_modules/tablet_options close
    polybar-msg -p $(cat /tmp/tablet_launcher_pid) cmd show
    echo open > $TMP_FILE
    polybar-msg -p $(cat /tmp/tablet_pid) hook applauncher 1
}

close() {
    polybar-msg -p $(cat /tmp/tablet_launcher_pid) cmd hide
    echo closed > $TMP_FILE
    polybar-msg -p $(cat /tmp/tablet_pid) hook applauncher 1
}

is_open() {
    if [ "$(cat $TMP_FILE)" == "open" ]; then
        return 0
    else
        return 1
    fi
}

toggle() {
    if is_open; then
        close
    else
        open
    fi
}

launch() {
    ID=$(cat $TMP_FILE)
    case "$1" in 
        chrome)
            firefox 
            ;;
        FileManager)
            thunar
            ;;
        Facebook)
            firefox https://facebook.com
            ;;
        twitter)
            firefox https://twitter.com/home
            ;;
        github)
            firefox https://github.com/urielzo
            ;;
        gmail)
            firefox https://mail.google.com
            ;;
        unixporn)
            firefox https://www.reddit.com/r/unixporn
            ;;
        youtube)
            firefox https://youtube.com
            ;;
        *)
            exit
    esac
    kill $ID
    close
}

icon() {
    COLOR_BASE="%{F#ffffff}"
    COLOR_ACTIVE="%{F#CCACB0}"
    COLOR_END="%{F-}"


    if is_open; then
        echo "$COLOR_ACTIVE  $COLOR_END"
    else
        echo "$COLOR_BASE  $COLOR_END"
    fi
}

case "$1" in
    launch)
        launch $2;;
    open)
        open;;
    close)
        close;;
    toggle)
        toggle;;
    icon)
        icon;;
    is_open)
        is_open;;
    *)
        echo "Unknown option $1"
        echo "applauncher [launch|open|close|toggle|is_open]"
esac


