#!/bin/bash

# Switch from tablet mode into normal desktop mode

killall onboard
killall unclutter

# rotate_display normal

# ./.config/i3/scripts/polybar_tablet close

./.config/i3/scripts/polybar_wrapper launch

# feh --randomize --bg-fill ~/.i3/wallpapers
