#!/bin/bash
create_bar() {
    polybar $1 &
    BAR_ID=$!
    echo PID = $BAR_ID
    WIN_ID=$(xdotool search --sync --pid $BAR_ID)
    echo $WIN_ID > $2
    xdotool windowunmap $WIN_ID
}

animation_open() {
    for BAR_ID in $@; do
        xdotool windowmap $BAR_ID
    done
    for y in `seq 40 10 0`; do
        for BAR_ID in $@; do
            xdotool windowmove $BAR_ID x $y
        done
    done
}

animation_close() {
    for y in `seq 0 -10 40`; do
        for BAR_ID in $@; do
            xdotool windowmove $BAR_ID x $y
        done
    done
    for BAR_ID in $@; do
        xdotool windowunmap $BAR_ID
    done
}

launch() {
    killall polybar
    polybar full &
    BAR_ID=$!
    rm -f /tmp/polybar_mqueue_full
    ln -s /tmp/polybar_mqueue.$BAR_ID /tmp/polybar_mqueue_full
   
}


case "$1" in
    rofi)
        rofi_open;;
    search)
        search_open;;
    options)
        options_open;;
    launch)
        launch;;
    hide)
        echo "cmd:hide" >> /tmp/polybar_mqueue_full;;
    show)
        echo "cmd:show" >> /tmp/polybar_mqueue_full;;
esac
